module.exports = {
  docs: [
    'Home',
    {
      type: 'category',
      label: 'ctfshow',
      items: [
        'ctfshow-xss',
        'ctfshow-xxe',
        'ctfshow-jwt',
        'ctfshow-nodejs',
        'ctfshow-phpcve',
        'ctfshow-sql注入',
        'ctfshow-ssrf',
        'ctfshow-ssti',
        'ctfshow-代码审计',
        'ctfshow-黑盒测试',
        'ctfshow-其他',
        'ctfshow-中期测评',
        'ctfshow-终极考核',
        'ctfshow-重温php特性',
        'ctfshow-重温反序列化',
        'ctfshow-重温命令执行',
        'ctfshow-8月赛吃瓜杯',
        'ctfshow-大赛原题（未完）',
      ],
    },
    {
      type: 'category',
      label: '硬件设计 - 应用方案',
      items: [
        'OSD335x最小系统的设计',
        '如何设计一款单片机的最小系统', // CSDN
        'STM32F4硬件开发',
        '直流有刷电机驱动的设计',
        'TinyDVR-小巧身材，满载动力',
        'RaptorDVR-集成稳压的30A双电机驱动',
        'SwiftCtrl-蓝牙手柄',
        'AirForce-充满灵性的电机驱动模块',
        'ZenDriver-高性能的电机驱动',
        '自制CMSIS-DAP',
        'PCB名片的设计',
        '防反接电路的设计',
        '电源的设计-常用芯片方案收集',
        '电源方案（Buck）-LMR14050',
      ],
    },

  ],
};

// 归档：
//'archive/Python学习笔记',
//'archive/STM32麦轮小车',
//'archive/RM校内赛-前期策划',
//'archive/报告书都要写些什么？',
//'archive/无人驾驶比赛',
//'archive/硬件模块',
//'archive/命令行基本操作'
//'archive/科技X的访谈',
//'archive/极简面包-烘培',
//'电路设计中常用的接口及关键点',
//'archive/Bash基础',
//'archive/从零搭建视觉开发环境（Docker-Linux）',
//'archive/Excel批量激活链接并转为图片',
//'archive/智能硬件产品开发流程',
//'archive/华广爬楼指北',
//'archive/小车游华广-比赛',
//'archive/麦昆小车-测评',
//'archive/STM32模块设计-LED',
//'archive/团队公开知识库的搭建',

// 未列出文章：
//'unlist/CentOS安装Docker',
//'unlist/Docker方式运行code-server',
//'unlist/T-Clock桌上小钟（旧）',
//'unlist/构建知识管理系统',
//'unlist/回归博客',
//'unlist/团队知识库搭建记录-DokuWiki',
//'unlist/个人知识库极简搭建指南-VuePress',
//'unlist/博客转至GitBook',
//'unlist/浅谈Bitcron博客平台',
//'unlist/基于docsify搭建个人Wiki',